### ISSUE TITLE
Embedding a sequence without finetuning

### ISSUE THREAD

**Issue by konstin** [mswzeus/PLUS#2]
Hi,

I'm working on [bio_embeddings](https://github.com/sacdallago/bio_embeddings/) ([poster](https://f1000research.com/posters/9-876), [talk](https://www.youtube.com/watch?v=NucUA0QiOe0)), a tool that embeds sequences using various methods, and we'd like to include PLUS-RNN as an embedding method.

For bio_embeddings, we generate embeddings from sequence without fine-tuning. Do you have an example of how to turn a sequence of amino acids into a sequence of embeddings with PLUS-RNN? Unfortunately I could only find examples that involve a `Trainer`.

I'm also working on making PLUS as publishable python package, you can see the current state [here](https://github.com/mswzeus/PLUS/compare/master...konstin:master).

**Comment by seonwoo-min** [comment]
@konstin, I apologize for the delayed response.

I have updated the codes to support generating protein sequence embeddings without fine-tuning.
You can now use the [plus_embedding.py](https://github.com/mswzeus/PLUS/blob/master/plus_embedding.py) file to turn protein sequences into sequences of embeddings with PLUS-RNN.
Given a FASTA file with protein sequences, the script generates and saves the PLUS-RNN representations as NumPy arrays.
For example, you can use the below command, assuming you have downloaded the pre-trained models.

<pre><code>
python plus_embedding.py --data-config config/data/embedding.json --model-config config/model/plus-rnn_large.json --run-config config/run/embedding.json --pretrained-model pretrained_models/PLUS-RNN_LARGE.pt --device 0 --output-path results/plus-rnn_large
</pre></code>

If you have any other questions or problems, please let me know!
