### ISSUE TITLE
Paper Appendix

### ISSUE THREAD

**Issue by yuanenming** [mswzeus/PLUS#3]
Very interesting work!
I am very curious about the details on pre-training and fine-tuning. However, I did not find supplementary information. So, where should I get the paper appendix?

**Comment by seonwoo-min** [comment]
Thank you for your interest in our work!

We are almost done revising the manuscript.
We plan to update the arXiv files once we are done with the revision, including the supplementary materials.
Please stay tuned for future arXiv updates for more details!

**Comment by yuanenming** [comment]
Thanks for your quick reply. I will follow the updates
